/**
 * Repository module exports
 * Provides unified access to all repository operations
 */

// Session Repository
export {
  createSession,
  getSessionBySenderId,
  getSessionById,
  updateSession,
  deleteSession,
  listSessions,
  countSessions,
  getOrCreateSession,
  updateSessionStatus,
  addTargetLocales as addSessionTargetLocales,
  getSessionsReadyForGitHub,
  cleanupExpiredSessions,
  type Session,
  type SessionType,
  type SessionStatus,
  type CreateSessionInput,
  type UpdateSessionInput,
  type SessionFilter,
} from './sessionRepository'

// File Repository
export {
  createFile,
  upsertFile,
  getFileById,
  getFile,
  updateFile,
  deleteFile,
  deleteFilesBySession,
  listFiles,
  getFilesBySessionGrouped,
  getUploadFiles,
  getTranslationFiles,
  getDeltaFiles,
  getOriginalFiles,
  countFiles,
  getFileStats,
  hasContentChanged,
  bulkCreateFiles,
  getLocalesForSession,
  type TranslationFile,
  type FileType,
  type ContentType,
  type FileFormat,
  type CreateFileInput,
  type UpdateFileInput,
  type FileFilter,
  type FileStats,
} from './fileRepository'

// Batch Repository
export {
  createBatch,
  getBatchByBatchId,
  getBatchById,
  updateBatch,
  deleteBatch,
  listBatches,
  countBatches,
  getPendingBatches,
  getBatchesForSession,
  markBatchSubmitted,
  markBatchCompleted,
  markBatchFailed,
  createBatchRequest,
  bulkCreateBatchRequests,
  getBatchRequests,
  getPendingBatchRequests,
  updateBatchRequestWithResponse,
  getBatchRequestByCustomId,
  getFailedBatchRequests,
  countBatchRequestsByStatus,
  type Batch,
  type BatchStatus,
  type OpenAIBatchStatus,
  type BatchManifest,
  type CreateBatchInput,
  type UpdateBatchInput,
  type BatchRequest,
  type BatchRequestStatus,
  type CreateBatchRequestInput,
  type BatchFilter,
} from './batchRepository'

// Translation Job Repository
export {
  createTranslationJob,
  getTranslationJob,
  getTranslationJobById,
  updateTranslationJob,
  deleteTranslationJob,
  listTranslationJobs,
  getJobsForSession,
  getOrCreateTranslationJob,
  updateGitHubIssue,
  updateGitHubPr,
  getJobsWithoutPr,
  countTranslationJobs,
  addTargetLocales as addJobTargetLocales,
  type TranslationJob,
  type JobType,
  type CreateTranslationJobInput,
  type UpdateTranslationJobInput,
  type TranslationJobFilter,
} from './translationJobRepository'

// Pipeline Repository
export {
  createPipelineEvent,
  getPipelineEventsBySession,
  getPipelineEventsBySenderId,
  getLatestEventsByStep,
  deletePipelineEventsBySession,
  deleteOldPipelineEvents,
  createApiRequestLog,
  getApiRequestLogsBySession,
  getApiRequestLogsBySenderId,
  deleteApiRequestLogsBySession,
  deleteOldApiRequestLogs,
  getPipelineLogCounts,
  clearSessionLogs,
  type PipelineEvent,
  type PipelineStep,
  type PipelineEventStatus,
  type ApiRequestLog,
  type CreatePipelineEventInput,
  type CreateApiRequestLogInput,
  type PipelineEventFilter,
  type ApiRequestLogFilter,
} from './pipelineRepository'
